# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 18:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.crypto
import functools
import trydiffoscope.compare.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_a', models.FileField(upload_to=functools.partial(trydiffoscope.compare.models.upload_to, *(), **{b'prefix': b'a'}))),
                ('file_b', models.FileField(upload_to=functools.partial(trydiffoscope.compare.models.upload_to, *(), **{b'prefix': b'b'}))),
                ('state', models.IntegerField(choices=[(b'queued', 10), (b'running', 20), (b'identical', 30), (b'different', 40), (b'error', 50), (b'timeout', 60)], default=10)),
                ('output', models.TextField()),
                ('slug', models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(12, b'abcdefghkpqrstuvxyz'), **{}), max_length=12, unique=True)),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('updated', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'ordering': ('-created',),
                'get_latest_by': 'created',
            },
        ),
    ]
