SITE_URL = '{{ site_url }}'
SECRET_KEY = '{{ secret_key }}'
MEDIA_ROOT = '{{ storage_dir }}'
DEFAULT_FROM_EMAIL = '{{ default_from_email }}'
TRYDIFFOSCOPE_MAX_UPLOAD_SIZE_MEGABYTES = '{{ client_max_body_size_megabytes }}'
